# Generated by Django 2.0.7 on 2019-06-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recicladores', '0002_auto_20190517_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitarAyuda',
        ),
    ]
